src/main/java/com/elec5619/orderapp/domain/Meal.java
package com.elec5619.orderapp.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table
public class Meal implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id()
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(nullable = false)
	private Integer id;
	@Column(nullable = false)
	private String mealName;
	@Column(nullable = false)
	private String mealDescription;
	@Column(nullable = false)
	private Integer mealPrice;
	@Column(nullable = false)
	private String mealImage;
	@ManyToOne(targetEntity=MealSeries.class)
	private MealSeries mealSeries;
	@Column(nullable = false)
	private String mealSummarize;
	@Column(nullable = false)
	private Integer rating;
	public Meal() {
		rating = 0;
	}
	public Meal(Integer id, String mealName, String mealDescription, Integer mealPrice, String mealImage,
			MealSeries mealSeries, String mealSummarize) {
		this.id = id;
		this.mealName = mealName;
		this.mealDescription = mealDescription;
		this.mealPrice = mealPrice;
		this.mealImage = mealImage;
		this.mealSeries = mealSeries;
		this.mealSummarize = mealSummarize;
		rating = 0;
	}
	
	
	public Integer getRating() {
		return rating;
	}
	public void setRating(Integer rating) {
		this.rating = rating;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getMealName() {
		return mealName;
	}
	public void setMealName(String mealName) {
		this.mealName = mealName;
	}
	public String getMealDescription() {
		return mealDescription;
	}
	public void setMealDescription(String mealDescription) {
		this.mealDescription = mealDescription;
	}
	public Double getMealPriceDouble() {
		return mealPrice/100.0;
	}
	public Integer getMealPrice() {
		return mealPrice;
	}
	public void setMealPrice(Integer mealPrice) {
		this.mealPrice = mealPrice;
	}
	public String getMealImage() {
		return mealImage;
	}
	public void setMealImage(String mealImage) {
		this.mealImage = mealImage;
	}
	public MealSeries getMealSeries() {
		return mealSeries;
	}
	public void setMealSeries(MealSeries mealSeries) {
		this.mealSeries = mealSeries;
	}
	public String getMealSummarize() {
		return mealSummarize;
	}
	public void setMealSummarize(String mealSummarize) {
		this.mealSummarize = mealSummarize;
	}
	@Override
	public String toString() {
		return "Meal [id=" + id + ", mealName=" + mealName + ", mealDescription=" + mealDescription + ", mealPrice="
				+ mealPrice + ", mealImage=" + mealImage + ", mealSeries=" + mealSeries + ", mealSummarize="
				+ mealSummarize + "]";
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((mealDescription == null) ? 0 : mealDescription.hashCode());
		result = prime * result + ((mealImage == null) ? 0 : mealImage.hashCode());
		result = prime * result + ((mealName == null) ? 0 : mealName.hashCode());
		result = prime * result + ((mealPrice == null) ? 0 : mealPrice.hashCode());
		result = prime * result + ((mealSeries == null) ? 0 : mealSeries.hashCode());
		result = prime * result + ((mealSummarize == null) ? 0 : mealSummarize.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Meal other = (Meal) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (mealDescription == null) {
			if (other.mealDescription != null)
				return false;
		} else if (!mealDescription.equals(other.mealDescription))
			return false;
		if (mealImage == null) {
			if (other.mealImage != null)
				return false;
		} else if (!mealImage.equals(other.mealImage))
			return false;
		if (mealName == null) {
			if (other.mealName != null)
				return false;
		} else if (!mealName.equals(other.mealName))
			return false;
		if (mealPrice == null) {
			if (other.mealPrice != null)
				return false;
		} else if (!mealPrice.equals(other.mealPrice))
			return false;
		if (mealSeries == null) {
			if (other.mealSeries != null)
				return false;
		} else if (!mealSeries.equals(other.mealSeries))
			return false;
		if (mealSummarize == null) {
			if (other.mealSummarize != null)
				return false;
		} else if (!mealSummarize.equals(other.mealSummarize))
			return false;
		return true;
	}
	
	
}

src/main/java/com/elec5619/orderapp/domain/Orders.java
package com.elec5619.orderapp.domain;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table
public class Orders implements Serializable{
	private static final long serialVersionUID = 1L;
	@Id()
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(nullable = false)
	private Integer id;
	
	@ManyToOne(targetEntity=Users.class)
	private Users user;
	@Column(nullable = false)
	private Date orderTime;
	@Column(nullable = false)
	private String orderState;
	@Column(nullable = false)
	private Integer orderPrice;
	@Column(nullable = false)
	private String addOn;
	@OneToMany(targetEntity=OrdersItem.class,cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private Set<OrdersItem> ordersItemSet;
	
	public Orders() {
	}

	public Orders(Integer id, Users user, Date orderTime, String orderState, Integer orderPrice, String addOn) {
		this.id = id;
		this.user = user;
		this.orderTime = orderTime;
		this.orderState = orderState;
		this.orderPrice = orderPrice;
		this.addOn = addOn;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}
	
	public String getOrderTimeStr() {
		SimpleDateFormat format = new SimpleDateFormat("HH:mm dd/MM/yyyy");
		return format.format(orderTime);
	}
	public Date getOrderTime() {
		return orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public String getOrderState() {
		return orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	
	public Set<OrdersItem> getOrdersItemSet() {
		return ordersItemSet;
	}

	public void setOrdersItemSet(Set<OrdersItem> ordersItemSet) {
		this.ordersItemSet = ordersItemSet;
	}

	public double getOrderPriceDouble() {
		
		return orderPrice/100.0;
	}
	public Integer getOrderPrice() {
		return orderPrice;
	}
	
	public void setOrderPrice(Integer orderPrice) {
		this.orderPrice = orderPrice;
	}

	public String getAddOn() {
		return addOn;
	}

	public void setAddOn(String addOn) {
		this.addOn = addOn;
	}

	@Override
	public String toString() {
		return "Orders [id=" + id + ", user=" + user + ", orderTime=" + orderTime + ", orderState=" + orderState
				+ ", orderPrice=" + orderPrice + ", addOn=" + addOn + ", ordersItemSet=" + ordersItemSet + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addOn == null) ? 0 : addOn.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((orderPrice == null) ? 0 : orderPrice.hashCode());
		result = prime * result + ((orderState == null) ? 0 : orderState.hashCode());
		result = prime * result + ((orderTime == null) ? 0 : orderTime.hashCode());
		result = prime * result + ((ordersItemSet == null) ? 0 : ordersItemSet.hashCode());
		result = prime * result + ((user == null) ? 0 : user.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Orders other = (Orders) obj;
		if (addOn == null) {
			if (other.addOn != null)
				return false;
		} else if (!addOn.equals(other.addOn))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (orderPrice == null) {
			if (other.orderPrice != null)
				return false;
		} else if (!orderPrice.equals(other.orderPrice))
			return false;
		if (orderState == null) {
			if (other.orderState != null)
				return false;
		} else if (!orderState.equals(other.orderState))
			return false;
		if (orderTime == null) {
			if (other.orderTime != null)
				return false;
		} else if (!orderTime.equals(other.orderTime))
			return false;
		if (ordersItemSet == null) {
			if (other.ordersItemSet != null)
				return false;
		} else if (!ordersItemSet.equals(other.ordersItemSet))
			return false;
		if (user == null) {
			if (other.user != null)
				return false;
		} else if (!user.equals(other.user))
			return false;
		return true;
	}

	
	
}

src/main/webapp/admin/infoOrders.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon"
	href="${pageContext.request.contextPath }/admin/img/favicon.png">
<title>Index</title>
<link
	href="${pageContext.request.contextPath }/admin/css/bootstrap.min.css"
	rel="stylesheet">
<link
	href="${pageContext.request.contextPath }/admin/css/bootstrap-theme.css"
	rel="stylesheet">
<link
	href="${pageContext.request.contextPath }/admin/css/elegant-icons-style.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/css/font-awesome.min.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/assets/fullcalendar/fullcalendar/fullcalendar.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css"
	rel="stylesheet" type="text/css" media="screen" />
<link rel="stylesheet"
	href="${pageContext.request.contextPath }/admin/css/owl.carousel.css"
	type="text/css">
<link
	href="${pageContext.request.contextPath }/admin/css/jquery-jvectormap-1.2.2.css"
	rel="stylesheet">
<link rel="stylesheet"
	href="${pageContext.request.contextPath }/admin/css/fullcalendar.css">
<link href="${pageContext.request.contextPath }/admin/css/widgets.css"
	rel="stylesheet">
<link href="${pageContext.request.contextPath }/admin/css/style.css"
	rel="stylesheet">
<link
	href="${pageContext.request.contextPath }/admin/css/style-responsive.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/css/xcharts.min.css"
	rel=" stylesheet">
<link
	href="${pageContext.request.contextPath }/admin/css/jquery-ui-1.10.4.min.css"
	rel="stylesheet">
</head>

<body ng-app="app" ng-controller="msCtrl">
	<section id="container" class="">
		<!--main content start-->
		<section id="main-content">
			<section class="wrapper">
				<!-- Form validations -->
				<div class="row">
					<div class="col-lg-12">
						<section class="panel">
							<header class="panel-heading">Order infomation</header>
							<section class="panel">
								<div class="panel-body bio-graph-info">
									<div class="row">
										<div class="bio-row">
											<p>
												<span>User name </span>: {{o.user.displayName}}
											</p>
										</div>
										<div class="bio-row">
											<p>
												<span>orderTime </span>: {{o.orderTimeStr}}
											</p>
										</div>
										<div class="bio-row">
											<p>
												<span>orderPrice</span>: {{o.orderPriceDouble}}
											</p>
										</div>
										<div class="bio-row">
											<p>
												<span>orderState </span>: {{o.orderState}}
											</p>
										</div>
										<div class="bio-row">
											<p>
												<span>addOn </span>: {{o.addOn}}
											</p>
										</div>
									</div>
									<div class="table-responsive">
										<h4 class="text-center">order items</h4>
										<table class="table">
											<tbody>
												<tr>
													<th>#</th>
													<th>MealName</th>
													<th>mealPrice</th>
													<th>mealCount</th>
												</tr>

												<tr ng-repeat="oi in o.ordersItemSet">
													<td><img width="50px" height="50px" alt="" src="{{oi.meal.mealImage}}"></td>
													<td>{{oi.meal.mealName}}</td>
													<td>{{oi.mealPriceDouble}}</td>
													<td>{{oi.mealCount}}</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</section>
					</div>
				</div>
			</section>
		</section>
		<!--main content end-->
	</section>
	<!-- container section start -->

	<!-- javascripts -->
	<script src="${pageContext.request.contextPath }/admin/js/jquery.js"></script>
	<script
		src="${pageContext.request.contextPath }/admin/js/bootstrap.min.js"></script>
	<!-- nice scroll -->
	<script
		src="${pageContext.request.contextPath }/admin/js/jquery.scrollTo.min.js"></script>
	<script
		src="${pageContext.request.contextPath }/admin/js/jquery.nicescroll.js"
		type="text/javascript"></script>
	<!-- jquery validate js -->
	<script type="text/javascript"
		src="${pageContext.request.contextPath }/admin/js/jquery.validate.min.js"></script>

	<!-- custom form validation script for this page-->
	<script
		src="${pageContext.request.contextPath }/admin/js/form-validation-script.js"></script>
	<!--custome script for all page-->
	<script src="${pageContext.request.contextPath }/admin/js/scripts.js"></script>
	<script
		src="${pageContext.request.contextPath }/common/js/angular.1.5.5.min.js"></script>

</body>

<script type="text/javascript">
	var app = angular.module("app",[]);
	app.controller("msCtrl",function($scope,$http){
		var id =document.URL.split("?")[1].split("=")[1];
		var url = "${pageContext.request.contextPath}/orders/getOrders.action?id="+id;
	  $http.post(url)
	    .then(function (result) {
	        $scope.o = result.data;
	    });
	});
</script>
</html>

src/main/webapp/admin/listOrders.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon"
	href="${pageContext.request.contextPath }/admin/img/favicon.png">
<title>Index</title>
<link
	href="${pageContext.request.contextPath }/admin/css/bootstrap.min.css"
	rel="stylesheet">
<link
	href="${pageContext.request.contextPath }/admin/css/bootstrap-theme.css"
	rel="stylesheet">
<link
	href="${pageContext.request.contextPath }/admin/css/elegant-icons-style.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/css/font-awesome.min.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/assets/fullcalendar/fullcalendar/fullcalendar.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css"
	rel="stylesheet" type="text/css" media="screen" />
<link rel="stylesheet"
	href="${pageContext.request.contextPath }/admin/css/owl.carousel.css"
	type="text/css">
<link
	href="${pageContext.request.contextPath }/admin/css/jquery-jvectormap-1.2.2.css"
	rel="stylesheet">
<link rel="stylesheet"
	href="${pageContext.request.contextPath }/admin/css/fullcalendar.css">
<link href="${pageContext.request.contextPath }/admin/css/widgets.css"
	rel="stylesheet">
<link href="${pageContext.request.contextPath }/admin/css/style.css"
	rel="stylesheet">
<link
	href="${pageContext.request.contextPath }/admin/css/style-responsive.css"
	rel="stylesheet" />
<link
	href="${pageContext.request.contextPath }/admin/css/xcharts.min.css"
	rel=" stylesheet">
<link
	href="${pageContext.request.contextPath }/admin/css/jquery-ui-1.10.4.min.css"
	rel="stylesheet">
</head>

<body ng-app="app" ng-controller="mslistCtrl">
	<section id="container" class="">
		<header class="header dark-bg">
			<div class="toggle-nav">
				<div class="icon-reorder tooltips"
					data-original-title="Toggle Navigation" data-placement="bottom"></div>
			</div>
			<a href="#" class="logo">Online <span class="lite">Food</span></a>

			<div class="top-nav notification-row">
				<!-- notificatoin dropdown start-->
				<ul class="nav pull-right top-menu">
					<!-- user login dropdown start-->
					<li class="dropdown"><a data-toggle="dropdown"
						class="dropdown-toggle" href="#"> <span class="profile-ava">
								<img width="40px" height="40px" alt="" src="${pageContext.request.contextPath }/admin/img/userdefault.jpg">
						</span> <span class="username">${Admin}</span> <b class="caret"></b>
					</a>
						<ul class="dropdown-menu extended logout">
							<div class="log-arrow-up"></div>
							<li><a href="${pageContext.request.contextPath }/user/adminExit.action"><i class="icon_key_alt"></i>
									Log Out</a></li>
						</ul></li>
					<!-- user login dropdown end -->
				</ul>
				<!-- notificatoin dropdown end-->
			</div>
		</header>
		<!--header end-->
		<!--sidebar start-->
		<aside>
			<div id="sidebar" class="nav-collapse ">
				<!-- sidebar menu start-->
				<ul class="sidebar-menu">
					<li ><a class="" href="${pageContext.request.contextPath }/admin/index.jsp"> <i
							class="icon_house_alt"></i> <span>Home</span>
					</a></li>
					<li class="sub-menu"><a href="javascript:;" class=""> <i
							class="icon_genius"></i> <span>MealSeries</span> <span
							class="menu-arrow arrow_carrot-right"></span>
					</a>
						<ul class="sub">
							<li><a class="" href="${pageContext.request.contextPath }/admin/addMealSeries.jsp">Add MealSeries</a></li>
							<li><a class="" href="${pageContext.request.contextPath }/admin/listMealSeries.jsp"><span>MealSeries
										List</span></a></li>
						</ul></li>

					<li class="sub-menu"><a href="javascript:;" class=""> <i
							class="icon_documents_alt"></i> <span>Meal Manage</span> <span
							class="menu-arrow arrow_carrot-right"></span>
					</a>
						<ul class="sub">
							<li><a class="" href="${pageContext.request.contextPath }/admin/listMeal.jsp"><span>Meal List</span></a></li>
						</ul></li>
					<li class="sub-menu active"><a href="javascript:;" class=""> <i
							class="icon_table"></i> <span>Order Manage</span> <span
							class="menu-arrow arrow_carrot-right"></span>
					</a>
						<ul class="sub">
							<li><a   href="${pageContext.request.contextPath }/admin/listOrders.jsp">Order List</a></li>
						</ul></li>



				</ul>
				<!-- sidebar menu end-->
			</div>
		</aside>
		<!--sidebar end-->

		<!--main content start-->
		<section id="main-content">
			<section class="wrapper">
				<div class="row">
					<div class="col-lg-12">
						<h3 class="page-header">
							<i class="fa fa-files-o"></i>Orders List
						</h3>
						<ol class="breadcrumb">
							<li><i class="fa fa-home"></i><a href="${pageContext.request.contextPath }/admin/index.jsp">Home</a></li>
							<li><i class="icon_document_alt"></i>Orders List</li>
						</ol>
					</div>
				</div>
				<!-- Form validations -->
				<div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                              Orders List
                          </header>
						 <div class="table-responsive">
                            <table class="table">
                           <tbody>
                              <tr>
                                 <th>#</th>
                                 <th>orderTime</th>
                                 <th>orderState</th>
                                 <th>orderPrice</th>
                                 <th>user</th>
                                 <th>Action</th>
                              </tr>
                             
                              <tr ng-repeat="o in orderslist">
                                 <td> {{o.id}}</td>
                                 <td> {{o.orderTimeStr}}</td>
                                 <td> {{o.orderState}}</td>
                                 <td> {{o.orderPrice/100}}</td>
                                 <td>{{o.user.displayName}}</td>
                                 <td width="15%">
                                  <div class="btn-group">
                                      <a class="btn btn-primary" href="#" ng-click="moreOrders(o.id)"><i class="icon_info_alt"></i></a>
                                      <a class="btn btn-success" ng-if="o.orderState=='Payed'" href="#" ng-click="sureOrders(o.id)"><i class="icon_check_alt2"></i></a>
                                       <a class="btn btn-primary" style="background-color: gray;" disabled ng-if="o.orderState!='Payed'"><i class="icon_check_alt2"></i></a>
                                  </div>
                                  </td>
                              </tr>
                                                      
                           </tbody>
                           <tfoot>
								<tr>
								<td colspan="8" class="text-center">cur:<span>{{curPage}}</span>/<span>{{allPage}}</span> &nbsp;&nbsp;
									<a href="#" ng-click="init_page_data('H')">Head</a>&nbsp;
									 <a href="#" ng-click="init_page_data('P')">Pre</a>&nbsp;
									 <a href="#" ng-click="init_page_data('N')">Next</a>&nbsp;
									 <a href="#" ng-click="init_page_data('T')"> Tail</a>
								</td>
								</tr>
							</tfoot>
                        </table>
                        </div>
                      </section>
                  </div>
              </div>
              
			</section>
		</section>
	
		<!--main content end-->
	</section>
	<!-- container section start -->

	<!-- javascripts -->
	<script src="${pageContext.request.contextPath }/admin/js/jquery.js"></script>
	<script
		src="${pageContext.request.contextPath }/admin/js/bootstrap.min.js"></script>
	<!-- nice scroll -->
	<script
		src="${pageContext.request.contextPath }/admin/js/jquery.scrollTo.min.js"></script>
	<script
		src="${pageContext.request.contextPath }/admin/js/jquery.nicescroll.js"
		type="text/javascript"></script>
	<!-- jquery validate js -->
	<script type="text/javascript"
		src="${pageContext.request.contextPath }/admin/js/jquery.validate.min.js"></script>

	<!-- custom form validation script for this page-->
	<script
		src="${pageContext.request.contextPath }/admin/js/form-validation-script.js"></script>
	<!--custome script for all page-->
	<script src="${pageContext.request.contextPath }/admin/js/scripts.js"></script>
	<script src="${pageContext.request.contextPath }/common/js/angular.1.5.5.min.js"></script>
	<script src="${pageContext.request.contextPath }/common/layer/layer.js"></script>

</body>

<script type="text/javascript">
	var app = angular.module("app",[]);
	app.controller("mslistCtrl",function($scope,$http){
	
		$scope.curPage = 1;
		$scope.init_page = function() {
			var url = "${pageContext.request.contextPath}/orders/countOrdersPage.action";
			$http.get(url).then(function(result){
				$scope.allPage = result.data;
			});
		}
		$scope.init_page_data = function(option)	{
			if(option == "H"){
				$scope.curPage = 1;
			}
			if(option == "T"){
				$scope.curPage = $scope.allPage;
			}
			if(option == "N") {
		
				if($scope.curPage <  $scope.allPage){
					++$scope.curPage;
				}
			}
			if(option == "P") {
				if($scope.curPage - 1 >= 1){
					--$scope.curPage;
				}
			}
			var url = "${pageContext.request.contextPath}/orders/findOrdersPage.action?page="+$scope.curPage;
			  $http.post(url)
			    .then(function (result) {
			        $scope.orderslist = result.data;
			    });
		};		
		$scope.sureOrders= function(id) {
			var url = "${pageContext.request.contextPath}/orders/confirmOrders.action?id="+id;
			  $http.post(url)
			    .then(function (result) {
			    	$scope.init_page_data(0);
			    });
		}
		$scope.moreOrders = function(id) {
			layer.open({
			  type: 2,
			  area: ["700px", "450px"],
			  fixed: false, 
			  maxmin: true,
			  title:"Order infomation",
			  cancel: function(index, layero){ 
				    layer.close(index);
				},
			  content: "${pageContext.request.contextPath }/admin/infoOrders.jsp?id="+id
			});
		};
		$scope.init_page();
		$scope.init_page_data(0);
	});
</script>
</html>