src/main/java/com/elec5619/orderapp/domain/Cart.java
package com.elec5619.orderapp.domain;

import java.io.Serializable;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table
public class Cart implements Serializable{
	private static final long serialVersionUID = 1L;
	@Id()
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(nullable = false)
	private Integer id;
	@Column(nullable = false)
	private Integer cartPrice;
	@Column(nullable = true)
	private String addOn;
	@OneToMany(targetEntity=CartItem.class,cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private Set<CartItem> cartItemSet;
	public Cart(Integer id,Integer cartPrice, String addOn) {
		super();
		this.id = id;
		this.cartPrice = cartPrice;
		this.addOn = addOn;
	}
	public Cart() {
		cartPrice = 0;
		addOn = "";
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Double getCartPriceDouble() {
		return cartPrice/100.0;
	}
	public Integer getCartPrice() {
		return cartPrice;
	}
	public void setCartPrice(Integer cartPrice) {
		this.cartPrice = cartPrice;
	}
	public String getAddOn() {
		return addOn;
	}
	public void setAddOn(String addOn) {
		this.addOn = addOn;
	}
	public Set<CartItem> getCartItemSet() {
		return cartItemSet;
	}
	public void setCartItemSet(Set<CartItem> cartItemSet) {
		this.cartItemSet = cartItemSet;
	}
	@Override
	public String toString() {
		return "Cart [id=" + id +  ", cartPrice=" + cartPrice + ", addOn=" + addOn + ", cartItemSet="
				+ cartItemSet + "]";
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addOn == null) ? 0 : addOn.hashCode());
		result = prime * result + ((cartItemSet == null) ? 0 : cartItemSet.hashCode());
		result = prime * result + ((cartPrice == null) ? 0 : cartPrice.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cart other = (Cart) obj;
		if (addOn == null) {
			if (other.addOn != null)
				return false;
		} else if (!addOn.equals(other.addOn))
			return false;
		if (cartItemSet == null) {
			if (other.cartItemSet != null)
				return false;
		} else if (!cartItemSet.equals(other.cartItemSet))
			return false;
		if (cartPrice == null) {
			if (other.cartPrice != null)
				return false;
		} else if (!cartPrice.equals(other.cartPrice))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
	
}

src/main/java/com/elec5619/orderapp/domain/Meal.java
package com.elec5619.orderapp.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table
public class Meal implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id()
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(nullable = false)
	private Integer id;
	@Column(nullable = false)
	private String mealName;
	@Column(nullable = false)
	private String mealDescription;
	@Column(nullable = false)
	private Integer mealPrice;
	@Column(nullable = false)
	private String mealImage;
	@ManyToOne(targetEntity=MealSeries.class)
	private MealSeries mealSeries;
	@Column(nullable = false)
	private String mealSummarize;
	@Column(nullable = false)
	private Integer rating;
	public Meal() {
		rating = 0;
	}
	public Meal(Integer id, String mealName, String mealDescription, Integer mealPrice, String mealImage,
			MealSeries mealSeries, String mealSummarize) {
		this.id = id;
		this.mealName = mealName;
		this.mealDescription = mealDescription;
		this.mealPrice = mealPrice;
		this.mealImage = mealImage;
		this.mealSeries = mealSeries;
		this.mealSummarize = mealSummarize;
		rating = 0;
	}
	
	
	public Integer getRating() {
		return rating;
	}
	public void setRating(Integer rating) {
		this.rating = rating;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getMealName() {
		return mealName;
	}
	public void setMealName(String mealName) {
		this.mealName = mealName;
	}
	public String getMealDescription() {
		return mealDescription;
	}
	public void setMealDescription(String mealDescription) {
		this.mealDescription = mealDescription;
	}
	public Double getMealPriceDouble() {
		return mealPrice/100.0;
	}
	public Integer getMealPrice() {
		return mealPrice;
	}
	public void setMealPrice(Integer mealPrice) {
		this.mealPrice = mealPrice;
	}
	public String getMealImage() {
		return mealImage;
	}
	public void setMealImage(String mealImage) {
		this.mealImage = mealImage;
	}
	public MealSeries getMealSeries() {
		return mealSeries;
	}
	public void setMealSeries(MealSeries mealSeries) {
		this.mealSeries = mealSeries;
	}
	public String getMealSummarize() {
		return mealSummarize;
	}
	public void setMealSummarize(String mealSummarize) {
		this.mealSummarize = mealSummarize;
	}
	@Override
	public String toString() {
		return "Meal [id=" + id + ", mealName=" + mealName + ", mealDescription=" + mealDescription + ", mealPrice="
				+ mealPrice + ", mealImage=" + mealImage + ", mealSeries=" + mealSeries + ", mealSummarize="
				+ mealSummarize + "]";
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((mealDescription == null) ? 0 : mealDescription.hashCode());
		result = prime * result + ((mealImage == null) ? 0 : mealImage.hashCode());
		result = prime * result + ((mealName == null) ? 0 : mealName.hashCode());
		result = prime * result + ((mealPrice == null) ? 0 : mealPrice.hashCode());
		result = prime * result + ((mealSeries == null) ? 0 : mealSeries.hashCode());
		result = prime * result + ((mealSummarize == null) ? 0 : mealSummarize.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Meal other = (Meal) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (mealDescription == null) {
			if (other.mealDescription != null)
				return false;
		} else if (!mealDescription.equals(other.mealDescription))
			return false;
		if (mealImage == null) {
			if (other.mealImage != null)
				return false;
		} else if (!mealImage.equals(other.mealImage))
			return false;
		if (mealName == null) {
			if (other.mealName != null)
				return false;
		} else if (!mealName.equals(other.mealName))
			return false;
		if (mealPrice == null) {
			if (other.mealPrice != null)
				return false;
		} else if (!mealPrice.equals(other.mealPrice))
			return false;
		if (mealSeries == null) {
			if (other.mealSeries != null)
				return false;
		} else if (!mealSeries.equals(other.mealSeries))
			return false;
		if (mealSummarize == null) {
			if (other.mealSummarize != null)
				return false;
		} else if (!mealSummarize.equals(other.mealSummarize))
			return false;
		return true;
	}
	
	
}

src/main/java/com/elec5619/orderapp/domain/MealSeries.java
package com.elec5619.orderapp.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table
public class MealSeries implements Serializable{
	private static final long serialVersionUID = 1L;
	@Id()
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(nullable = false)
	private Integer id;
	@Column(nullable = false)
	private String seriesName;
	
	public MealSeries() {
	}

	public MealSeries(Integer id, String seriesName) {
		this.id = id;
		this.seriesName = seriesName;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSeriesName() {
		return seriesName;
	}

	public void setSeriesName(String seriesName) {
		this.seriesName = seriesName;
	}

	@Override
	public String toString() {
		return "MealSeries [id=" + id + ", seriesName=" + seriesName + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((seriesName == null) ? 0 : seriesName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MealSeries other = (MealSeries) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (seriesName == null) {
			if (other.seriesName != null)
				return false;
		} else if (!seriesName.equals(other.seriesName))
			return false;
		return true;
	}
	
	
}

src/main/java/com/elec5619/orderapp/domain/Orders.java
package com.elec5619.orderapp.domain;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table
public class Orders implements Serializable{
	private static final long serialVersionUID = 1L;
	@Id()
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(nullable = false)
	private Integer id;
	
	@ManyToOne(targetEntity=Users.class)
	private Users user;
	@Column(nullable = false)
	private Date orderTime;
	@Column(nullable = false)
	private String orderState;
	@Column(nullable = false)
	private Integer orderPrice;
	@Column(nullable = false)
	private String addOn;
	@OneToMany(targetEntity=OrdersItem.class,cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private Set<OrdersItem> ordersItemSet;
	
	public Orders() {
	}

	public Orders(Integer id, Users user, Date orderTime, String orderState, Integer orderPrice, String addOn) {
		this.id = id;
		this.user = user;
		this.orderTime = orderTime;
		this.orderState = orderState;
		this.orderPrice = orderPrice;
		this.addOn = addOn;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}
	
	public String getOrderTimeStr() {
		SimpleDateFormat format = new SimpleDateFormat("HH:mm dd/MM/yyyy");
		return format.format(orderTime);
	}
	public Date getOrderTime() {
		return orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public String getOrderState() {
		return orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	
	public Set<OrdersItem> getOrdersItemSet() {
		return ordersItemSet;
	}

	public void setOrdersItemSet(Set<OrdersItem> ordersItemSet) {
		this.ordersItemSet = ordersItemSet;
	}

	public double getOrderPriceDouble() {
		
		return orderPrice/100.0;
	}
	public Integer getOrderPrice() {
		return orderPrice;
	}
	
	public void setOrderPrice(Integer orderPrice) {
		this.orderPrice = orderPrice;
	}

	public String getAddOn() {
		return addOn;
	}

	public void setAddOn(String addOn) {
		this.addOn = addOn;
	}

	@Override
	public String toString() {
		return "Orders [id=" + id + ", user=" + user + ", orderTime=" + orderTime + ", orderState=" + orderState
				+ ", orderPrice=" + orderPrice + ", addOn=" + addOn + ", ordersItemSet=" + ordersItemSet + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addOn == null) ? 0 : addOn.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((orderPrice == null) ? 0 : orderPrice.hashCode());
		result = prime * result + ((orderState == null) ? 0 : orderState.hashCode());
		result = prime * result + ((orderTime == null) ? 0 : orderTime.hashCode());
		result = prime * result + ((ordersItemSet == null) ? 0 : ordersItemSet.hashCode());
		result = prime * result + ((user == null) ? 0 : user.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Orders other = (Orders) obj;
		if (addOn == null) {
			if (other.addOn != null)
				return false;
		} else if (!addOn.equals(other.addOn))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (orderPrice == null) {
			if (other.orderPrice != null)
				return false;
		} else if (!orderPrice.equals(other.orderPrice))
			return false;
		if (orderState == null) {
			if (other.orderState != null)
				return false;
		} else if (!orderState.equals(other.orderState))
			return false;
		if (orderTime == null) {
			if (other.orderTime != null)
				return false;
		} else if (!orderTime.equals(other.orderTime))
			return false;
		if (ordersItemSet == null) {
			if (other.ordersItemSet != null)
				return false;
		} else if (!ordersItemSet.equals(other.ordersItemSet))
			return false;
		if (user == null) {
			if (other.user != null)
				return false;
		} else if (!user.equals(other.user))
			return false;
		return true;
	}

	
	
}

src/main/java/com/elec5619/orderapp/domain/OrdersItem.java
package com.elec5619.orderapp.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table
public class OrdersItem implements Serializable{
	private static final long serialVersionUID = 1L;
	@Id()
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(nullable = false)
	private Integer id;
	@ManyToOne(targetEntity=Meal.class)
	private Meal meal;
	
	@Column(nullable = false)
	private Integer mealPrice;
	
	@Column(nullable = false)
	private Integer mealCount;
	@Column(nullable=false)
	private Integer commentState;
	
	public OrdersItem() {
		commentState = 0;
	}
	public OrdersItem(Integer id, Meal meal, Integer mealPrice, Integer mealCount) {
		this.id = id;
		this.meal = meal;
		this.mealPrice = mealPrice;
		this.mealCount = mealCount;
		commentState = 0;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Meal getMeal() {
		return meal;
	}
	public void setMeal(Meal meal) {
		this.meal = meal;
	}
	public Double getMealPriceDouble() {
		return mealPrice/100.0;
	}
	public Integer getMealPrice() {
		return mealPrice;
	}
	public void setMealPrice(Integer mealPrice) {
		this.mealPrice = mealPrice;
	}
	public Integer getMealCount() {
		return mealCount;
	}
	public void setMealCount(Integer mealCount) {
		this.mealCount = mealCount;
	}
	public String getCommentStateStr() {
		if(commentState.equals(0)) {
			return "UnComment";
		}else{
			return "Comment";
		}
	}
	public Integer getCommentState() {
		return commentState;
	}
	public void setCommentState(Integer commentState) {
		this.commentState = commentState;
	}
	@Override
	public String toString() {
		return "OrdersItem [id=" + id + ", meal=" + meal + ", mealPrice=" + mealPrice + ", mealCount=" + mealCount
				+ ", commentState=" + commentState + "]";
	}
	
}

src/main/webapp/page/orderInfo.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!DOCTYPE html>
<html>
<head>
<title>OrderInfo</title>
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript">
	 addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } 
</script>
<!-- //Custom Theme files -->
<link href="${pageContext.request.contextPath }/page/css/bootstrap.css"
	type="text/css" rel="stylesheet" media="all">
<link href="${pageContext.request.contextPath }/page/css/style.css"
	type="text/css" rel="stylesheet" media="all">
<!-- js -->
<script src="${pageContext.request.contextPath }/page/js/jquery.min.js"></script>
<script type="text/javascript"
	src="${pageContext.request.contextPath }/page/js/bootstrap-3.1.1.min.js"></script>
<!-- //js -->
<!-- cart -->
<script
	src="${pageContext.request.contextPath }/page/js/simpleCart.min.js">
	
</script>
<!-- cart -->
</head>
<body ng-app="app" ng-controller="pageCtrl">
	<!--header-->
	<div class="header">
		<div class="container">
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse"
						data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span> <span
							class="icon-bar"></span> <span class="icon-bar"></span> <span
							class="icon-bar"></span>
					</button>
					<h1 class="navbar-brand">
						<a href="${pageContext.request.contextPath}/page/index.jsp">OnlineFood</a>
					</h1>
				</div>
				<!--navbar-header-->
				<div class="collapse navbar-collapse"
					id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li><a
							href="${pageContext.request.contextPath}/page/index.jsp"
							class="active">Home</a></li>
						<li class="dropdown grid"><a href="#"
							class="dropdown-toggle list1" data-toggle="dropdown">Meal
								Series<b class="caret"></b>
						</a>
							<ul class="dropdown-menu multi-column columns-3">
								<div class="row">
									<div class="col-sm-4 col-md-4">
										<ul class="multi-column-dropdown">
											<li><a class="list"
												href="${pageContext.request.contextPath}/page/mealSeries.jsp">All</a></li>
											<li><a class="list"
												href="${pageContext.request.contextPath}/page/mealSeries.jsp?seriesId={{i.id}}"
												ng-repeat="i in ms">{{i.seriesName}}</a></li>
										</ul>
									</div>
								</div>
							</ul></li>
					</ul>
					<!--/.navbar-collapse-->
				</div>
				<!--//navbar-header-->
			</nav>
			<div class="header-info">
				<div class="header-right search-box">
					<a href="#"><span class="glyphicon glyphicon-search"
						aria-hidden="true"></span></a>
					<div class="search">
						<form class="navbar-form">
							<input ng-model="keyword" type="text" class="form-control">
							<button type="submit" ng-click="search()" class="btn btn-default"
								aria-label="Left Align">Search</button>
						</form>
					</div>
				</div>
				<div class="header-right login">
					<a href="#"><span class="glyphicon glyphicon-user"
						aria-hidden="true"></span></a>
					<c:if test="${user == null}">
						<div id="loginBox">

							<form id="loginForm">
								<fieldset id="body">
									<fieldset>
										<label for="email">Login Name</label> <input type="text"
											ng-model="loginName" name="loginName" />
									</fieldset>
									<fieldset>
										<label for="password">Password</label> <input type="password"
											ng-model="loginPwd" name="password">
									</fieldset>
									<span class="btn" id="login">Sign in</span>
								</fieldset>
								<p>
									New User ? <a class="sign"
										href="${pageContext.request.contextPath }/page/sign-up.jsp">Sign
										Up</a>
								</p>
							</form>



						</div>
					</c:if>

					<c:if test="${user != null}">
						<div id="loginBox">
							<form id="loginForm">
								<fieldset id="body">
									<fieldset>
										<span>Welcome:${user.displayName }</span>
									</fieldset>
									<fieldset>
										<a class="btn btn-default" ng-click="update_user()">profile</a>
									</fieldset>
									<fieldset>
										<a class="btn btn-default" href="${pageContext.request.contextPath }/page/orders.jsp">my orders</a>
									</fieldset>
									<fieldset>
										<a class="btn btn-default"
											href="${pageContext.request.contextPath }/user/logoutUsers.action">Logout</a>
									</fieldset>

								</fieldset>
							</form>
						</div>
					</c:if>
				</div>
				<div class="header-right cart">
					<a href="#"><span class="glyphicon glyphicon-shopping-cart"
						aria-hidden="true"></span></a>
					<div class="cart-box">
						<c:if test="${user != null}">
							<h4><a href="${pageContext.request.contextPath }/page/cart.jsp">
									<span> <span>$</span>${user.cart.cartPriceDouble } </span> (<span> ${fn:length(user.cart.cartItemSet)} </span>) 
								</a></h4>
							<p><a href="${pageContext.request.contextPath }/page/cart.jsp" class="simpleCart_empty">view cart</a></p>
							<div class="clearfix"> </div>
						</c:if>
						
						<c:if test="${user == null}">
							<h4><a href="#">
								<span> $0.00 </span> (<span > 0 </span>) 
							</a></h4>
							<p><a href="javascript:;" class="simpleCart_empty">Empty cart</a></p>
							<div class="clearfix"> </div>
						</c:if> 
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	<!--//header-->
	<!--cart-items-->
	<div class="cart-items">
		<div class="container">
			<h2 >Orders &nbsp;&nbsp;&nbsp;&nbsp;
				All Price(<span>$</span>{{orders.orderPriceDouble }})&nbsp;&nbsp;&nbsp;&nbsp;
				AddOn:{{orders.addOn }}
			</h2>
			<c:if test="${user!=null}">
				<div class="cart-header" ng-repeat="c in orders.ordersItemSet">
					<div class="cart-sec simpleCart_shelfItem">
						<div class="cart-item cyc">
							<img src="{{c.meal.mealImage}}" class="img-responsive" alt="">
						</div>
						<div class="cart-item-info">
							<h3>
								<a href="#"> {{c.meal.mealName}} </a><span>$&nbsp;{{c.meal.mealPriceDouble}}</span>
							</h3>
							<ul class="qty">
								<li><p>quantity:&nbsp;&nbsp;
								<span>{{c.mealCount}}</span>
								</p></li>
								<li><p>
									{{c.commentStateStr}}
								</p></li>
							</ul>
							<div class="delivery">
								<button class="btn btn-default" ng-if="c.commentState == 0" ng-click="comment(c.id)">Comment</button>
								<button class="btn btn-default" ng-if="c.commentState == 1" disabled="disabled">Comment</button>
								<div class="clearfix"></div>
							</div>	
							
						</div>
						<div class="clearfix"></div>
					</div>
				</div>

			</c:if>
		</div>
	</div>
	<!--//checkout-->
	<!--//footer-->
	<div class="footer-bottom">
		<div class="container">
			<p>Copyright &copy; 2017.Online food order app.</p>
		</div>
	</div>
</body>
<script src="${pageContext.request.contextPath }/common/js/angular.1.5.5.min.js"></script>
<script src="${pageContext.request.contextPath }/common/layer/layer.js"></script>
<script type="text/javascript">
	var app = angular.module("app", []);
	app.controller("pageCtrl",function($scope, $http) {
		$http.post("${pageContext.request.contextPath }/mealSeries/findMSAll.action").then(function(result) {
			$scope.ms = result.data;
		});
		var id = document.URL.split("?")[1].split("=")[1];
		var url = "${pageContext.request.contextPath }/orders/getOrders.action?id="+id;
		$http.post(url).then(function(result){
			$scope.orders = result.data;
		});	
		$scope.comment = function(id){
			layer.open({
				  type: 2,
				  area: ["700px", "450px"],
				  fixed: false, 
				  maxmin: true,
				  title:"Comment",
				  cancel: function(index, layero){ 
					    layer.close(index);
					    window.location.reload();
					},
				  content: "${pageContext.request.contextPath }/page/addComment.jsp?id="+id
				});
		}
		
		$scope.update_user = function() {
			layer.open({
				  type: 2,
				  area: ["700px", "450px"],
				  fixed: false, 
				  maxmin: true,
				  title:"Update user",
				  cancel: function(index, layero){ 
					    layer.close(index);
					    window.location.reload();
					},
				  content: "${pageContext.request.contextPath }/page/updateUser.jsp"
				});
		}
		$scope.range = function(length) {
			var json = new Array(length);
			for (var i = 0; i < length; i++) {
				json[i] = i;
			}
			return json;
		}
		$scope.search = function() {
			if ($scope.keyword == null || $scope.keyword == "") {
				alert("please input keyword you want to search");
				return;
			}
			window.location.href = "${pageContext.request.contextPath}/page/mealSeries.jsp?keyword="
					+ $scope.keyword;
		};
		$("#login").click(function() {
			if ($scope.loginName == ""
					|| $scope.loginName == null) {
				alert("please input Login Name");
				return;
			}
			if ($scope.loginPwd == ""
					|| $scope.loginPwd == null) {
				alert("please input login Password");
				return;
			}
			var url = "${pageContext.request.contextPath}/user/loginUsers.action";
			$.ajax({
						type : "post",
						url : url,
						data : {
							"loginName" : $scope.loginName,
							"loginPwd" : $scope.loginPwd
						},
						success : function(data) {
							if (data == 0) {
								alert("user isn't exist or password wrong");
								return;
							}
							window.location.reload();
						}
					});
		});

	});
</script>
</html>